apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: tickets
spec:
  replicas: 1
  selector:
    matchLabels: { app: mongodb }
  template:
    metadata:
      labels: { app: mongodb }
    spec:
      containers:
        - name: mongodb
          image: mongo:7
          args: ["--bind_ip_all"]     # listen on all interfaces
          ports:
            - containerPort: 27017
          readinessProbe:
            tcpSocket: { port: 27017 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket: { port: 27017 }
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}                 # ephemeral (fine for local dev)
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: tickets
spec:
  selector: { app: mongodb }
  ports:
    - port: 27017
      targetPort: 27017
      name: mongo
  type: ClusterIP