apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: tickets
spec:
  replicas: 1
  selector:
    matchLabels: { app: api }
  template:
    metadata:
      labels: { app: api }
    spec:
      containers:
        - name: api
          image: tickets-api:dev 
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: MONGO_URL
              value: "mongodb://mongodb:27017/tickets"
          ports:
            - containerPort: 3000            # echo-server listens on 80
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: tickets
spec:
  selector: { app: api }
  ports:
    - name: http
      port: 3000
      targetPort: 3000                        # forward service→pod 3000→3000
  type: ClusterIP
