name: Deploy frontend to GitHub Pages

on:
  push:
    branches: [ main ]     # ← change 'main' if your default branch is called something else
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install deps
        run: npm ci

      - name: Build (GitHub Pages)
        env:
          VITE_BASE_PATH: ${{ vars.VITE_BASE_PATH }}   # e.g. /tickets-app/
          VITE_USE_HASH_ROUTER: 'true'
          VITE_API_BASE: ${{ vars.VITE_API_BASE }}     # e.g. https://ticketchart-api.onrender.com
          VITE_SOCKET_URL: ${{ vars.VITE_SOCKET_URL }} # same as above
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
